### ISSUE TITLE
Exposed env variables

### ISSUE THREAD

**Issue by danieljohnson18** [gandalf-network/whoami#69]
Hi whoami team, great work on building an amazing product. Was taking some time to look through the codebase and I noticed some env variables that are exposed. I'm not sure if this was an oversight or not, just thought to bring it to your attention 

#src/helpers/constants.ts

[https://github.com/gandalf-network/whoami/blob/main/src/helpers/constants.ts](url)

Again, great work

**Comment by TosinJs** [comment]
Hello @danieljohnson18, thank you for taking the time to review the codebase and for bringing this to our attention!

The environment variables you've noticed in #src/helpers/constants.ts are indeed exposed intentionally. They are provided as part of the setup to simplify the initial configuration process for developers who are deploying the project. These variables are generic enough to not compromise any security but specific enough to serve as examples for setting up their own environments.

If you have any more observations or suggestions, please feel free to share them. Your contributions help make the project better for everyone!

**Comment by danieljohnson18** [comment]
Okay, thanks for the heads up. 

Keep up the good work!
